-- MySQL Script generated by MySQL Workbench
-- Mon Sep 13 13:31:24 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tienda_organica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tienda_organica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tienda_organica` DEFAULT CHARACTER SET utf8mb4 ;
USE `tienda_organica` ;

-- -----------------------------------------------------
-- Table `tienda_organica`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda_organica`.`clientes` (
  `cedula_cliente` BIGINT(20) NOT NULL,
  `nombre_clientelibro` VARCHAR(255) NULL DEFAULT NULL,
  `email_cliente` VARCHAR(255) NULL DEFAULT NULL,
  `direccion_cliente` VARCHAR(255) NULL DEFAULT NULL,
  `telefono_cliente` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`cedula_cliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tienda_organica`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda_organica`.`proveedores` (
  `nitproveedor` BIGINT(20) NOT NULL,
  `nombre_proveedor` VARCHAR(255) NULL DEFAULT NULL,
  `ciudad_proveedor` VARCHAR(255) NULL DEFAULT NULL,
  `direccion_proveedor` VARCHAR(255) NULL DEFAULT NULL,
  `telefono_proveedor` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`nitproveedor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tienda_organica`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda_organica`.`productos` (
  `codigo_producto` BIGINT(20) NOT NULL,
  `nombre_producto` VARCHAR(255) NULL DEFAULT NULL,
  `nitproveedor` BIGINT(20) NULL DEFAULT NULL,
  `precio_compra` DOUBLE NULL DEFAULT NULL,
  `iva_compra` DOUBLE NULL DEFAULT NULL,
  `precio_venta` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`codigo_producto`),
  INDEX `nitproveedor` (`nitproveedor` ASC) VISIBLE,
  CONSTRAINT `productos_ibfk_1`
    FOREIGN KEY (`nitproveedor`)
    REFERENCES `tienda_organica`.`proveedores` (`nitproveedor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tienda_organica`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda_organica`.`empleados` (
  `cedula_empleado` BIGINT(20) NOT NULL,
  `nombre_empleado` VARCHAR(255) NULL DEFAULT NULL,
  `email_cliente` VARCHAR(255) NULL DEFAULT NULL,
  `nombre_usuario` VARCHAR(255) NULL DEFAULT NULL,
  `contraseña` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`cedula_empleado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tienda_organica`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda_organica`.`ventas` (
  `codigo_venta` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `cedula_cliente` BIGINT(20) NULL DEFAULT NULL,
  `cedula_empleado` BIGINT(20) NULL DEFAULT NULL,
  `nitproveedor` BIGINT(20) NULL DEFAULT NULL,
  `iva_venta` DOUBLE NULL DEFAULT NULL,
  `total_venta` DOUBLE NULL DEFAULT NULL,
  `valor_venta` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`codigo_venta`),
  INDEX `cedula_cliente` (`cedula_cliente` ASC) VISIBLE,
  INDEX `cedula_empleado` (`cedula_empleado` ASC) VISIBLE,
  CONSTRAINT `ventas_ibfk_1`
    FOREIGN KEY (`cedula_cliente`)
    REFERENCES `tienda_organica`.`clientes` (`cedula_cliente`),
  CONSTRAINT `ventas_ibfk_2`
    FOREIGN KEY (`cedula_empleado`)
    REFERENCES `tienda_organica`.`empleados` (`cedula_empleado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tienda_organica`.`detalle_ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda_organica`.`detalle_ventas` (
  `codigo_detalle_venta` BIGINT(20) NOT NULL,
  `cantidad_producto` INT(11) NULL DEFAULT NULL,
  `codigo_producto` BIGINT(20) NULL DEFAULT NULL,
  `codigo_venta` BIGINT(20) NULL DEFAULT NULL,
  `valor_venta` DOUBLE NULL DEFAULT NULL,
  `valor_iva_venta` DOUBLE NULL DEFAULT NULL,
  `valor_total` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`codigo_detalle_venta`),
  INDEX `codigo_producto` (`codigo_producto` ASC) VISIBLE,
  INDEX `codigo_venta` (`codigo_venta` ASC) VISIBLE,
  CONSTRAINT `detalle_ventas_ibfk_1`
    FOREIGN KEY (`codigo_producto`)
    REFERENCES `tienda_organica`.`productos` (`codigo_producto`),
  CONSTRAINT `detalle_ventas_ibfk_2`
    FOREIGN KEY (`codigo_venta`)
    REFERENCES `tienda_organica`.`ventas` (`codigo_venta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
